# Generated by Django 6.0.1 on 2026-01-20 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARDIO', 'Cardio'), ('FUERZA', 'Entrenamiento de Fuerza'), ('YOGA', 'Yoga/Flexibilidad'), ('NATACION', 'Natación')], default='CARDIO', max_length=20)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Tiempo en minutos')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('calorias_quemadas', models.PositiveIntegerField(help_text='Calorías quemadas durante la actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
