# Generated by Django 6.0.1 on 2026-02-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0002_alter_actividad_calorias_quemadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
            ],
            options={
                'verbose_name': 'Tipo de Ejercicio',
                'verbose_name_plural': 'Tipos de Ejercicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='calorias_quemadas',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='duracion_minutos',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='tipo',
        ),
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='Entrenamiento', max_length=100, verbose_name='Nombre de la sesión'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='exampleapp.actividad')),
                ('tipo_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exampleapp.tipoejercicio', verbose_name='Ejercicio')),
            ],
        ),
    ]
